# Generated by Django 3.2.11 on 2022-03-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_auto_20220224_1357"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="first_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="student",
            name="last_name",
            field=models.CharField(default="", max_length=255),
        ),
    ]
